# Generated by Django 5.2.8 on 2025-11-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
                ('shares', models.FloatField()),
                ('purchase_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
