# Generated by Django 5.2.8 on 2025-12-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_adminemail_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
