# Generated by Django 5.2.8 on 2025-12-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_position_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
